name: Say Hi

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Say Hi
      run: |
        echo "Issue title: ${{ github.event.pull_request.title }}"
      env:
          FLAG: ${{ secrets.FLAG }}
